# https://www.appveyor.com/docs/appveyor-yml/
#---------------------------------#
#      general configuration      #
#---------------------------------#
version: '{build}'
skip_tags: true
max_jobs: 1
#---------------------------------#
#    environment configuration    #
#---------------------------------#
clone_depth: 30
environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
    - JAVA_HOME: C:\Program Files\Java\jdk11
matrix:
  fast_finish: true
cache:
  - C:\Users\appveyor\.m2\ -> pom.xml
install:
  - SET PATH=%PATH%;.
  - cmd: SET MAVEN_OPTS=-Xmx1g
  - cmd: SET JAVA_OPTS=-Xmx1g
  - cmd: mvnw --version
  - cmd: java -version
#---------------------------------#
#       build configuration       #
#---------------------------------#
build:
  parallel: true
before_build:
  - mvnw clean -B
build_script:
  - mvnw package -B
#---------------------------------#
#       tests configuration       #
#---------------------------------#
test_script:
  - mvnw test verify -B
